# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1563, 970)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.object_add = QtWidgets.QPushButton(self.centralwidget)
        self.object_add.setObjectName("object_add")
        self.gridLayout.addWidget(self.object_add, 0, 1, 1, 1)
        self.class_add = QtWidgets.QPushButton(self.centralwidget)
        self.class_add.setObjectName("class_add")
        self.gridLayout.addWidget(self.class_add, 0, 2, 1, 1)
        self.class_rm = QtWidgets.QPushButton(self.centralwidget)
        self.class_rm.setObjectName("class_rm")
        self.gridLayout.addWidget(self.class_rm, 1, 2, 1, 1)
        self.rmimagebutton = QtWidgets.QPushButton(self.centralwidget)
        self.rmimagebutton.setObjectName("rmimagebutton")
        self.gridLayout.addWidget(self.rmimagebutton, 1, 0, 1, 1)
        self.object_rm = QtWidgets.QPushButton(self.centralwidget)
        self.object_rm.setObjectName("object_rm")
        self.gridLayout.addWidget(self.object_rm, 1, 1, 1, 1)
        self.loadimagebutton = QtWidgets.QPushButton(self.centralwidget)
        self.loadimagebutton.setObjectName("loadimagebutton")
        self.gridLayout.addWidget(self.loadimagebutton, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.objects_list = Treeview(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.objects_list.sizePolicy().hasHeightForWidth())
        self.objects_list.setSizePolicy(sizePolicy)
        self.objects_list.setMinimumSize(QtCore.QSize(395, 0))
        self.objects_list.setMouseTracking(True)
        self.objects_list.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.objects_list.setLineWidth(2)
        self.objects_list.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.objects_list.setAutoScrollMargin(10)
        self.objects_list.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.objects_list.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.objects_list.setResizeGripsVisible(True)
        self.objects_list.setObjectName("objects_list")
        self.verticalLayout.addWidget(self.objects_list)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 2, 1, 1)
        self.outline_toggle = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outline_toggle.sizePolicy().hasHeightForWidth())
        self.outline_toggle.setSizePolicy(sizePolicy)
        self.outline_toggle.setMinimumSize(QtCore.QSize(150, 0))
        self.outline_toggle.setObjectName("outline_toggle")
        self.gridLayout_2.addWidget(self.outline_toggle, 2, 0, 1, 1)
        self.overviewbutton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overviewbutton.sizePolicy().hasHeightForWidth())
        self.overviewbutton.setSizePolicy(sizePolicy)
        self.overviewbutton.setObjectName("overviewbutton")
        self.gridLayout_2.addWidget(self.overviewbutton, 1, 0, 1, 1)
        self.zoombutton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoombutton.sizePolicy().hasHeightForWidth())
        self.zoombutton.setSizePolicy(sizePolicy)
        self.zoombutton.setMinimumSize(QtCore.QSize(150, 0))
        self.zoombutton.setObjectName("zoombutton")
        self.gridLayout_2.addWidget(self.zoombutton, 2, 1, 1, 1)
        self.panbutton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.panbutton.sizePolicy().hasHeightForWidth())
        self.panbutton.setSizePolicy(sizePolicy)
        self.panbutton.setObjectName("panbutton")
        self.gridLayout_2.addWidget(self.panbutton, 1, 1, 1, 1)
        self.toolbarwidget = QtWidgets.QWidget(self.centralwidget)
        self.toolbarwidget.setEnabled(False)
        self.toolbarwidget.setObjectName("toolbarwidget")
        self.gridLayout_2.addWidget(self.toolbarwidget, 2, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.mpl_widget = MplCanvas(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_widget.sizePolicy().hasHeightForWidth())
        self.mpl_widget.setSizePolicy(sizePolicy)
        self.mpl_widget.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.mpl_widget.setObjectName("mpl_widget")
        self.verticalLayout_2.addWidget(self.mpl_widget)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1563, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpenImages = QtWidgets.QAction(MainWindow)
        self.actionOpenImages.setObjectName("actionOpenImages")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionOpenProject = QtWidgets.QAction(MainWindow)
        self.actionOpenProject.setObjectName("actionOpenProject")
        self.actionSaveProject = QtWidgets.QAction(MainWindow)
        self.actionSaveProject.setObjectName("actionSaveProject")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionExportLabels = QtWidgets.QAction(MainWindow)
        self.actionExportLabels.setObjectName("actionExportLabels")
        self.actionOpen_settings = QtWidgets.QAction(MainWindow)
        self.actionOpen_settings.setObjectName("actionOpen_settings")
        self.actionOpen_help = QtWidgets.QAction(MainWindow)
        self.actionOpen_help.setObjectName("actionOpen_help")
        self.actionSelect_colormap = QtWidgets.QAction(MainWindow)
        self.actionSelect_colormap.setObjectName("actionSelect_colormap")
        self.actionAdd_object = QtWidgets.QAction(MainWindow)
        self.actionAdd_object.setObjectName("actionAdd_object")
        self.actionRemove_object = QtWidgets.QAction(MainWindow)
        self.actionRemove_object.setObjectName("actionRemove_object")
        self.actionRemove_all_objects = QtWidgets.QAction(MainWindow)
        self.actionRemove_all_objects.setObjectName("actionRemove_all_objects")
        self.actionAdd_class = QtWidgets.QAction(MainWindow)
        self.actionAdd_class.setObjectName("actionAdd_class")
        self.actionRemove_class = QtWidgets.QAction(MainWindow)
        self.actionRemove_class.setObjectName("actionRemove_class")
        self.actionSwitch_outlines_on_off = QtWidgets.QAction(MainWindow)
        self.actionSwitch_outlines_on_off.setObjectName("actionSwitch_outlines_on_off")
        self.menuFile.addAction(self.actionOpenImages)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpenProject)
        self.menuFile.addAction(self.actionSaveProject)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExportLabels)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionOpen_help)
        self.menuView.addAction(self.actionSwitch_outlines_on_off)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionSelect_colormap)
        self.menuSettings.addAction(self.actionOpen_settings)
        self.menuEdit.addAction(self.actionAdd_object)
        self.menuEdit.addAction(self.actionRemove_object)
        self.menuEdit.addAction(self.actionRemove_all_objects)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionAdd_class)
        self.menuEdit.addAction(self.actionRemove_class)
        self.menuEdit.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CALM Labelling Tool"))
        self.object_add.setText(_translate("MainWindow", "Add object"))
        self.class_add.setText(_translate("MainWindow", "Add class"))
        self.class_rm.setText(_translate("MainWindow", "Remove class"))
        self.rmimagebutton.setText(_translate("MainWindow", "Remove Image"))
        self.object_rm.setText(_translate("MainWindow", "Remove object"))
        self.loadimagebutton.setText(_translate("MainWindow", "Load Image"))
        self.outline_toggle.setText(_translate("MainWindow", "Turn outlines off"))
        self.overviewbutton.setText(_translate("MainWindow", "Image overview"))
        self.zoombutton.setText(_translate("MainWindow", "Activate zoom"))
        self.panbutton.setText(_translate("MainWindow", "Activate pan"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpenImages.setText(_translate("MainWindow", "Open images"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionOpenProject.setText(_translate("MainWindow", "Open Project"))
        self.actionSaveProject.setText(_translate("MainWindow", "Save Project"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionExportLabels.setText(_translate("MainWindow", "Export Labels"))
        self.actionOpen_settings.setText(_translate("MainWindow", "Open settings"))
        self.actionOpen_help.setText(_translate("MainWindow", "Open help"))
        self.actionSelect_colormap.setText(_translate("MainWindow", "Select colormap"))
        self.actionAdd_object.setText(_translate("MainWindow", "Add object"))
        self.actionRemove_object.setText(_translate("MainWindow", "Remove object"))
        self.actionRemove_all_objects.setText(_translate("MainWindow", "Remove all objects"))
        self.actionAdd_class.setText(_translate("MainWindow", "Add class"))
        self.actionRemove_class.setText(_translate("MainWindow", "Remove class"))
        self.actionSwitch_outlines_on_off.setText(_translate("MainWindow", "Switch outlines on/off"))

from vision import MplCanvas, Treeview

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

